apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-history-server.name" . }}-s3
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  accessKey: {{ .Values.s3.accessKey | quote }}
  secretKey: {{ .Values.s3.secretKey | quote }}

